/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package CRUD_OPS;
import com.Item;
import java.util.*;
import javax.persistence.*;


public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
    EntityManager manager;
    public Library() {
    	EntityManagerFactory em=Persistence.createEntityManagerFactory("ItemPU");
    	manager = em.createEntityManager();
    	
    }
    
    public void saveItem(Item item) {
    	manager.getTransaction().begin();
    	manager.persist(item);
    	manager.getTransaction().commit();
    }
    
    public Item getItem(int id) {
    	Item item=manager.find(Item.class, id);
    	return item;
    }
    
    public void updateItem(Item item,int id) {
    	Item contender = getItem(id);
    	contender.setName(item.getName());
    	contender.setPrice(item.getPrice());
    	manager.getTransaction().begin();
    	manager.flush();
    	manager.getTransaction().commit();
    	
    }
    
    public void removeItem(int id) {
    	Item contender=getItem(id);
    	manager.getTransaction().begin();
    	manager.flush();
    	manager.remove(contender);
    	manager.getTransaction().commit();
    }
    public void jpql() {
    	
    	List<Item> list=manager.createQuery("Select i from Item i").getResultList();
    	for(Item obj:list) {
    		System.out.println(obj.toString());
    	}    	
    }
    public void namedParameterDemo(int iprice) {
    	String query="Select i from Item i where i.price=:price";
    	Query paramQuery=manager.createQuery(query);
    	paramQuery.setParameter("price",iprice);
    	
    	List<Item>  itemList=paramQuery.getResultList();
    	for(Item obj:itemList) {
    		System.out.println(obj.toString());
    	}
    }
    
    
    public static void main(String[] args) { 
    	Library lib=new Library();
    	lib.saveItem(new Item("shampoo",68));
    	lib.saveItem(new Item("cheese",109));
    	lib.saveItem(new Item("milk",54));
    	lib.saveItem(new Item("butter",50));
    	lib.saveItem(new Item("peanuts",120));
    	lib.saveItem(new Item("ghee",750));
    	lib.saveItem(new Item("bread",30));
    	lib.saveItem(new Item("jam",50));
    	lib.saveItem(new Item("rice",80));
    	lib.jpql();
    	lib.namedParameterDemo(50);
    	
    	
//    	Item item=new Item();
//    	Item item2=new Item();
//    
//    	item.setName("Deodrant");
//    	item.setPrice(200);
//    	lib.saveItem(item);
//    	item2.setName("facewash");
//    	item2.setPrice(50);
//    	lib.saveItem(item2);
//    	
//    	System.out.println(lib.getItem(1).toString());
//    	System.out.println(lib.getItem(2).toString());
//    	
//    	item.setName("Changed name");
//    	item.setPrice(20);
//    	
//    	System.out.println(lib.getItem(1).toString());
//    	System.out.println(lib.getItem(2).toString());
//    	
//    	
//    	
//    	lib.removeItem(2);
//    	
    	
		
	}
}
