/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package hghg;
import javax.persistence.*;


import com.Pet;
import com.PetStore;
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
    public static void main(String[] args) {
		System.out.println("#############");
		EntityManagerFactory emf=Persistence.createEntityManagerFactory("PetPU");
		EntityManager entityManager=emf.createEntityManager();
		
		Pet pet=new Pet(1,"doggo","DOG",2);
		Pet pet2=new Pet(2,"Katie","Cat",1);
		
		
		PetStore ps=new PetStore("Pstore", "Delhi-12");
		PetStore ps2=new PetStore("paw store", "Delhi-91");
		
		entityManager.getTransaction().begin();
		entityManager.persist(pet2);
		entityManager.persist(pet);
		entityManager.persist(ps);
		entityManager.persist(ps2);
		entityManager.flush();
		entityManager.getTransaction().commit();
	}
    
}
