/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package SpringDemo;
import org.checkerframework.checker.units.qual.s;
import org.springframework.context.ApplicationContext;
import org.springframework.context.support.ClassPathXmlApplicationContext;
import com.*;
import java.util.List;
import java.util.Map;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
    public static void main(String[] args) {
		System.out.println("hi bro!");
		
		ApplicationContext context=new ClassPathXmlApplicationContext("springbean.xml");
//		Human human1=context.getBean("human",Human.class);
//		System.out.println(human1.toString());
		 
		Department dept=context.getBean("department",Department.class);		
		System.out.println("name= " +dept.getH().getName());
		System.out.println("salary= "+dept.getH().getSalary());
		System.out.println("all details \t "+dept.toString());
	
	
		
		
		Attendance adt=context.getBean("attendance",Attendance.class);
		if(adt.isPresent()) {
			System.out.println("present");
		}
		else {
			System.out.println("absent");
		}
		
		//list here
		List<Human> humanList=dept.getHumanList();
		for(Human h: humanList) {
			System.out.println("-----------human list details---------------");
			System.out.println(h.getName());
			System.out.println(h.getSalary());
		}
		
		
		System.out.println("---------------Item class here--------------------");
		
		Item it=context.getBean("item1",Item.class);
		System.out.println(it.getItemName());
		System.out.println(it.getPrice());
		
		
		
		
		
		//hashmap here
		HashmapDemo hmd=context.getBean("mapExample",HashmapDemo.class);
		
		Map<Integer,Human> projectList=hmd.getProjectList();
		System.out.println("------------hashmap details below-----------------");
		for(Integer i:projectList.keySet()) {
			Human x= projectList.get(i);
			System.out.println(x.getName());
			System.out.println(x.getSalary());
		}
		
		
		
		//sales class here
		
		Sales sales=context.getBean("saleList",Sales.class);
		List<Item> itemList=sales.getItemList();
		System.out.println("----------------sales class list here-----------");
		for(Item i: itemList) {
			System.out.println(i.getItemName());
			System.out.println(i.getPrice());
		}
		
		
		
		
		
	} 
}
